#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Eacherator
version:      0.01
version_from: lib/Data/Eacherator.pm
installdirs:  perl
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
